version: 2

project_name: saml2aws

builds:
  - id: saml2aws-windows
    main: ./cmd/saml2aws/main.go
    binary: saml2aws
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -v
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=0

archives:
  - id: saml2aws-windows-archive
    ids:
      - saml2aws-windows
    formats:
      - zip
    wrap_in_directory: false
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_windows_checksums.txt"
