version: 2

project_name: saml2aws

builds:
  - id: saml2aws-macos
    main: ./cmd/saml2aws/main.go
    binary: saml2aws
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
      - -v
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - id: saml2aws-tarball
    ids:
      - saml2aws-macos
    formats:
      - tar.gz
    wrap_in_directory: false
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_checksums.txt"
